# Generated by Django 5.0 on 2024-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='companyName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
