# Generated by Django 5.0 on 2024-05-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_companydetails_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='surname',
        ),
    ]
