# Generated by Django 5.0 on 2024-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_hosting_description_remove_hosting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingpackage',
            name='selectPackages',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('standard', 'Standard'), ('premium', 'Premium'), ('gold', 'Gold')], max_length=150),
        ),
    ]
