# Generated by Django 5.0 on 2024-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_hostingpackage_selectpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='livechatUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
