# Generated by Django 5.0 on 2024-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_companydetails_livechaturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingpackage',
            name='storage',
            field=models.CharField(max_length=200),
        ),
    ]
