# Generated by Django 5.0 on 2024-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_hostingpackage_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingpackage',
            name='domain',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hostingpackage',
            name='support',
            field=models.CharField(max_length=200),
        ),
    ]
