# Generated by Django 5.0 on 2024-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hostingpackage_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='Serviceimage/'),
            preserve_default=False,
        ),
    ]
