# Generated by Django 5.0 on 2024-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_companydetails_companydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='companyDescription',
            field=models.TextField(),
        ),
    ]
