# Generated by Django 5.0 on 2024-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='gif',
            field=models.ImageField(default=1, upload_to='gif'),
            preserve_default=False,
        ),
    ]
